eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service:
      url:
        defalutZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservice:
  PaymentService:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/PaymentService/payment/do
  OrderService:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/OrderService/order/book
